/** Converts an AADP resource type (`^[a-z][a-z0-9_-]*$`) into a camelCase identifier, e.g. `"blog-post"` -> `"blogPost"`. */
export function toCamelCase(type: string): string {
  return type
    .split(/[-_]/)
    .filter(Boolean)
    .map((part, i) => (i === 0 ? part : part[0].toUpperCase() + part.slice(1)))
    .join("");
}

export function initTemplate(): string {
  return `/**
 * AADP v1.0 server config, generated by \`aadp init\`.
 * https://github.com/ailmao-app/aadp
 */
import { defineAADP } from "ail-aadp/server";
// import { postResource } from "./resources/post.js";

export const aadp = defineAADP({
  baseUrl: "https://example.com", // TODO: your production origin, no trailing slash
  application: {
    name: "TODO: application name",
    description: "TODO: one-sentence description of what this application publishes",
    publisher: {
      name: "TODO: publisher name",
      url: "https://example.com",
    },
  },
  policies: {
    robots: "https://example.com/robots.txt",
    terms: "https://example.com/terms",
  },
  resources: [
    // postResource,
  ],
});

/**
 * Wire this into your framework's route handlers — \`handleRequest\` is a
 * plain \`(Request) => Promise<Response>\`, so no adapter is needed. For a
 * Next.js App Router project:
 *
 *   // app/.well-known/ai-manifest.json/route.ts
 *   export { aadp } from "../../../aadp/aadp.server";
 *   export const GET = aadp.handleRequest;
 *
 *   // app/ai/1.0/sitemap-index.json/route.ts
 *   // app/ai/1.0/sitemaps/[type].json/route.ts
 *   // app/ai/1.0/entities/[type]/[id].json/route.ts
 *   export const GET = aadp.handleRequest;
 *
 * Run \`npx aadp add-resource <type>\` to scaffold a new resource file
 * under ./resources, then import it above and add it to "resources".
 */
`;
}

export function resourceTemplate(type: string): string {
  const name = toCamelCase(type);
  return `import { defineResource } from "ail-aadp/server";

/**
 * TODO: replace \`unknown\` with the domain record type for "${type}".
 */
export const ${name}Resource = defineResource<unknown>({
  type: "${type}",

  // TODO: return one page of public "${type}" records. \`cursor\` is an
  // opaque string this resource minted on a previous call (via
  // \`nextCursor\`), or \`null\` on the first page — this package never
  // interprets it. May call a database, an internal API, or anything
  // else; \`defineAADP()\` never assumes a data source.
  list: async ({ cursor, limit }) => {
    return { items: [], nextCursor: null };
  },

  // TODO: resolve one public "${type}" record by the id segment recovered
  // from its entity URL (the same id \`serialize()\` reports below).
  // Return null/undefined if it does not exist or is not public.
  get: async ({ id }) => {
    return null;
  },

  // TODO: return ONLY public fields in \`data\` — this is the one place a
  // raw record may leak into a published document. \`id\` MUST be
  // \`"${type}:" + <the id get() expects>\`.
  serialize: (record) => {
    throw new Error('serialize() for resource "${type}" is not implemented yet');
  },
});
`;
}
